### ISSUE TITLE
abilitiesfolder

### ISSUE THREAD

**Issue by DivisorOfZero** [Arackulele/GrimoraMod#1]
So I downloaded 1.1.1 from the Thunderstore manager and it would break every time I tried to start a new game so I brought up the logger and it was showing that it was trying to grab the abilities folder directly from the Plugins folder not inside the Arackulele-GrimoraMod folder

![Bug](https://user-images.githubusercontent.com/95166280/143763088-cd50dba7-6994-4ba5-bfa6-43bb6b963fdd.png)

I manage to make it work by just copying the files into the plugins folder directly.

**Comment by keifersisawesome** [comment]
I've got this problem as well.

**Comment by julian-perge** [comment]
This issue should be fixed with the upcoming v2.1 release.
