### ISSUE TITLE
plenty of cards in deck selection menu are missing sigils

### ISSUE THREAD

**Issue by inversefireman** [Arackulele/GrimoraMod#101]
heres some sigils, dont like dolls but that sigils really hard to draw anyway, didnt do tomb robber because its in act 2 also, but still isnt there
![grimorasigils](https://user-images.githubusercontent.com/131537927/233790443-c121af66-8dfe-4456-86e0-939f97ba2ce3.png)

**Comment by Arackulele** [comment]
These will be added thanks for submitting,

Also add a Label to your issues when you open them

**Comment by inversefireman** [comment]
i do not know how to do that, github is a mystery to me

**Comment by Arackulele** [comment]
done
