### ISSUE TITLE
Gravedigger + Fledging converts Gravedigger into Sporedigger without transforming its name along with its new form

### ISSUE THREAD

**Issue by Unihedro** [Arackulele/GrimoraMod#102]
![20230422231213_1](https://user-images.githubusercontent.com/5595067/233790290-2158666e-38dc-4b07-a40c-7a822c4d6bab.jpg)

Maybe fledging on these cards just aren't a good idea overall, but it's too late to nerf the sigil :D (note: bone king was already there and not part of fledging)

**Comment by Arackulele** [comment]
https://imgur.com/a/f0639iq

This works fine as of the latest version
