### ISSUE TITLE
Beta: Catacombs miniboss with rule "Random sigil gets added to cards every turn" doesn't work for activated sigils (and potentially some other more)

### ISSUE THREAD

**Issue by Unihedro** [Arackulele/GrimoraMod#104]
![20230422233710_1](https://user-images.githubusercontent.com/5595067/233791068-b26f800b-8641-405b-b355-dd1ae06f130b.jpg)

Clicking on the Disinter sigil doesn't give skeletons (with 5 bones in hand)

**Comment by Arackulele** [comment]
Can confirm this is an issue with activated Sigils, i will remove them from the list of sigils to be added by that specific rule
