### ISSUE TITLE
dialogue inconsistencies

### ISSUE THREAD

**Issue by inversefireman** [Arackulele/GrimoraMod#105]
grimora first implies youre simply digging up an existing corpse, after doing so she instead says you were burying your card

![image](https://user-images.githubusercontent.com/131537927/233802695-cfdadf0f-301d-476d-89d4-826877004b86.png)
![image](https://user-images.githubusercontent.com/131537927/233802737-68f685db-9a7b-43cf-8f9c-9c9bdeaa70fc.png)

**Comment by Arackulele** [comment]
fixed the ending dialogue to mention that they dug up the corpse, instead of being buried themselves
