### ISSUE TITLE
sniper haunter/amorphous bug

### ISSUE THREAD

**Issue by inversefireman** [Arackulele/GrimoraMod#106]
"If Apparition gets the Sniper sigil, it will try to load in the custom Sniper arm animation resulting in a softlock, same thing happens if a card with Sentry and Haunter dies, and Sentry gets passed onto another card

Sniper error:
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GrimoraMod.VisualizeSniperPatches.VisualizeStartSniperAbilityGrimora (DiskCardGame.CardSlot sniperSlot) (at <f64b3f8562874473862bc233be909670>:0)
DiskCardGame.CombatPhaseManager.VisualizeStartSniperAbility (DiskCardGame.CardSlot sniperSlot) (at <da2b996d8a794aeea3b45a93cee1351d>:0)
InscryptionCommunityPatch.Card.SniperFix+<SniperAttack>d__2.MoveNext () (at <8349ac84860540479f8082ea7a270d08>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)" -Wise Scholar, Catboy Stinkbug

**Comment by Arackulele** [comment]
As this seems to be a conflict with the API, haunter now replaces the Sniper and Sentry Sigils with slasher when they haubnt a slot. Grimora will remark with a flavor Text about how ghosts cannot transfer modern Technology like that.
