### ISSUE TITLE
Soft lock after picking item from tomb

### ISSUE THREAD

**Issue by VioletSkies19** [Arackulele/GrimoraMod#122]
It offered me 3 blank cards in bottles. I picked the middle one. Soft lock. 

Here are the latest errors in log 

[Error  : Unity Log] Coroutine couldn't be started because the the game object 'DynamicElements' is inactive!
[Warning: Singleton] Got null in Singleton<DiskCardGame.CandleHolder>.FindInstance
[Info   :GrimoraMod] [ChangeLogicInCardAbilityIcons] GrimoraSaveUtil.IsNotGrimoraModRun False
[Info   :GrimoraMod] [ChangeLogicInCardAbilityIcons] GrimoraSaveUtil.IsNotGrimoraModRun False
[Info   :GrimoraMod] [ChangeLogicInCardAbilityIcons] GrimoraSaveUtil.IsNotGrimoraModRun False
[Info   :GrimoraMod] [ChangeLogicInCardAbilityIcons] GrimoraSaveUtil.IsNotGrimoraModRun False
[Info   :GrimoraMod] [ChangeLogicInCardAbilityIcons] GrimoraSaveUtil.IsNotGrimoraModRun False
[Info   :GrimoraMod] [ChangeLogicInCardAbilityIcons] GrimoraSaveUtil.IsNotGrimoraModRun False
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
InscryptionAPI.Items.ConsumableItemManager+ItemSlot_CreateItem.Prefix (DiskCardGame.ItemSlot __instance, DiskCardGame.ItemData data, System.Boolean skipDropAnimation) (at <39937c18fde94bc6980f9423c14a10e3>:0)
DiskCardGame.ItemSlot.CreateItem (DiskCardGame.ItemData data, System.Boolean skipDropAnimation) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.ConsumableItemSlot.CreateItem (DiskCardGame.ItemData data, System.Boolean skipDropAnimation) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.ConsumableItemSlot.CreateItem (System.String itemName, System.Boolean skipDropAnimation) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.ItemsManager.UpdateItems (System.Boolean immediate) (at <4bde92741da1454db82522c215e393a6>:0)
GrimoraMod.GrimoraGainConsumableSequencer+<RegularGainConsumables>d__2.MoveNext () (at <4a7a83b6bfc1414a95352cfcc034995c>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by VioletSkies19** [comment]
Was on a Grimora map if it matters

**Comment by VioletSkies19** [comment]
I would like to add. I did get the item after reloading. It was a rabbit card

**Comment by Arackulele** [comment]
closed as this does not seem to be a consistent bug, i will close this for now, open a new report if this happens again
