### ISSUE TITLE
Arrow key controls are wonky

### ISSUE THREAD

**Issue by VioletSkies19** [Arackulele/GrimoraMod#124]
Using arrow key movement on the board has weird behavior with the up and right arrows. Often accidentally checking my deck or looking at items when I’m just trying to move. 

I know the mouse works but it’s much less comfortable

**Comment by Arackulele** [comment]
This is because the arrow keys are already bound to different actions in inscryption, in the grimora mod configuration you can change the controls for that to wasd if you want

**Comment by Arackulele** [comment]
IJKL movement system exists now
