### ISSUE TITLE
Frozen on black screen after losing to bone lord

### ISSUE THREAD

**Issue by VioletSkies19** [Arackulele/GrimoraMod#125]
Losing to bone lord freezes me on a black screen and throws this error:

[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
GrimoraMod.Saving.GrimoraRunState.NewStandardGame () (at <4a7a83b6bfc1414a95352cfcc034995c>:0)
GrimoraMod.Saving.GrimoraSaveFile.NewStandardRun () (at <4a7a83b6bfc1414a95352cfcc034995c>:0)
GrimoraMod.Saving.GrimoraSaveManager.ResetStandardRun () (at <4a7a83b6bfc1414a95352cfcc034995c>:0)
GrimoraMod.Saving.GrimoraSaveManager.ResetRun () (at <4a7a83b6bfc1414a95352cfcc034995c>:0)
GrimoraMod.TransitionExt+<TransitionToGame2>d__1.MoveNext () (at <4a7a83b6bfc1414a95352cfcc034995c>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by Arackulele** [comment]
I'm gonna need more information on this loosing to the bone lord does not softlock me so it is probably caused by some other parameter

**Comment by VioletSkies19** [comment]
Not sure what triggered it. Will watch for it happening again
