### ISSUE TITLE
soflock with ourobornes steel trap giants

### ISSUE THREAD

**Issue by VioletSkies19** [Arackulele/GrimoraMod#129]
my ourobones has steel trap, frozen away, puppeteer, and cold front. crashes when one of the twins kills it

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DiskCardGame.Card.RenderCard () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.PlayableCard.UpdateStatsText () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.PlayableCard.OnStatsChanged () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.PlayableCard.RemoveTemporaryMod (DiskCardGame.CardModificationInfo mod, System.Boolean updateDisplay) (at <4bde92741da1454db82522c215e393a6>:0)
GrimoraMod.Puppeteer+<AddBrittleBack>d__13.MoveNext () (at <7529fb60e72c42d2ad00140ffbb17c08>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by VioletSkies19** [comment]
same crash different error 

[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Component.GetComponent[T] () (at <3f8c35799b544274b189c23afcaaf82e>:0)
DiskCardGame.Card.get_Anim () (at <4bde92741da1454db82522c215e393a6>:0)
GrimoraMod.CombatPhaseManagerPatches+<HandleSpecificAttacksForCustomAnims>d__1.MoveNext () (at <7529fb60e72c42d2ad00140ffbb17c08>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by VioletSkies19** [comment]
doesn't seem to happen if i kill it with the hammer

**Comment by Arackulele** [comment]
steel trap bug, this has nothing to do with ourobones

**Comment by Arackulele** [comment]
this is now fixed
