### ISSUE TITLE
Suggestion: Rare cards add an additional point worth of sigils when being sacrificed in the Reaper Node.

### ISSUE THREAD

**Issue by BlindTheBoundDemon** [Arackulele/GrimoraMod#134]
So a rare card with 3 sigils counts as a common card with 4 sigils.

A rare card with 5 sigils unlocks a new tier of outcomes: 25% chance to gain a buff to the entire deck and 75% chance to gain the Major Boon effect.

**Comment by Arackulele** [comment]
added in the upcoming update
