### ISSUE TITLE
Suggestion to change the icon of the Leader sigil to fit more with the style of Grimora

### ISSUE THREAD

**Issue by BlindTheBoundDemon** [Arackulele/GrimoraMod#138]
![LeaderHand](https://user-images.githubusercontent.com/51028657/234619131-948680a9-72e3-4b6b-873b-68cf21c63f62.png)
![LeaderSkull](https://user-images.githubusercontent.com/51028657/234619137-4b38a6e8-7f6a-47af-95e4-e06d284f76cc.png)

i made two version of how the new icon could look like, feel free to use one of them

**Comment by Arackulele** [comment]
probably not gonna be changed for now but thanks
