### ISSUE TITLE
soft lock when using soul shot on apperition to attack a frozen away bone hound 

### ISSUE THREAD

**Issue by VioletSkies19** [Arackulele/GrimoraMod#141]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GrimoraMod.GraveControllerExt.PlaySpecificAttackAnimation (System.String animToPlay, System.Boolean attackPlayer, DiskCardGame.CardSlot targetSlot, System.Action impactCallback) (at <991aac787d164fedb797d3b77f10e86a>:0)
GrimoraMod.CardRelatedExtension.PlaySpecificAttackAnimation (DiskCardGame.CardAnimationController controller, System.String animToPlay, System.Boolean attackPlayer, DiskCardGame.CardSlot targetSlot, System.Action impactCallback) (at <991aac787d164fedb797d3b77f10e86a>:0)
GrimoraMod.ActivatedDealDamageGrimora+<Activate>d__7.MoveNext () (at <991aac787d164fedb797d3b77f10e86a>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by Arackulele** [comment]
The issue with Activated abilities and ahunter has been fixed, not the animation issue. If possible , please try to create less specific issues in the future as this is another duplicate
