### ISSUE TITLE
Amorphous transformed into nothing

### ISSUE THREAD

**Issue by Nevernamed22** [Arackulele/GrimoraMod#145]
I had a Gravedigger with Bone Digger, Amorphous, and Stinky (the last two from the Electric chair). Once, when I drew the card, it played the transform animation but just lost amorphous, and gained no other sigils. It also didn't generate two bones. Maybe it tried to give itself a second stinky?
No errors in the log.

**Comment by Arackulele** [comment]
fxied in an upcoming update
