### ISSUE TITLE
Dead hand bug

### ISSUE THREAD

**Issue by Kensen07** [Arackulele/GrimoraMod#146]
BUG REPORT I just dead hand on bone lord with 4 cards left in my main deck, had the animation of me drawing cards but cards goes away! (Hopefully I was lethal but making -4 CA instead of +5 is a bit wierd lol)

(I used dead hand tool in the same game before, idk if this is important)

**Comment by Arackulele** [comment]
Closed as this is just a visual bug not a gameplay bug, also the visual bug is fixed in an upcoming version
