### ISSUE TITLE
La Llorona doesn't have an emission

### ISSUE THREAD

**Issue by BlindTheBoundDemon** [Arackulele/GrimoraMod#148]
![image](https://user-images.githubusercontent.com/51028657/235321707-e9fd57f2-9ead-49a2-89f3-93e5eb311eed.png)

**Comment by VioletSkies19** [comment]
sometimes i have noticed cards not having their emissions the first turn or two after being drawn. not sure if this is the same issue

**Comment by Arackulele** [comment]
Fixed in upcoming update
