### ISSUE TITLE
soft lock involving ourobones and haunter

### ISSUE THREAD

**Issue by VioletSkies19** [Arackulele/GrimoraMod#149]
played an ourobones card with inverted strike, sniper, and haunter.
After it died i placed a animator card in its space.
Everything seemed normal besides the cumulative torment sigil not applying to animator. When the animator attacked it soft locked with this error

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GrimoraMod.VisualizeSniperPatches.VisualizeStartSniperAbilityGrimora (DiskCardGame.CardSlot sniperSlot) (at <991aac787d164fedb797d3b77f10e86a>:0)
DiskCardGame.CombatPhaseManager.VisualizeStartSniperAbility (DiskCardGame.CardSlot sniperSlot) (at <4bde92741da1454db82522c215e393a6>:0)
InscryptionCommunityPatch.Card.SniperFix+<SniperAttack>d__2.MoveNext () (at <f54d4fd1dccf41be85923d2be1e7f7d0>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by VioletSkies19** [comment]
update its the ouro causing it. happens with any card not just animator

**Comment by Arackulele** [comment]
Closing this because it is a Bug relating to the Sniper Visualization, not any specific Cards, so this is a duplicate
