### ISSUE TITLE
Game freezes in Sawyer Patel boss fight!

### ISSUE THREAD

**Issue by TrueSerpentKing** [Arackulele/GrimoraMod#150]
The game freezes after ending my turn when the Hell Hound Jumps in front of the Apparition card with the sentry sigil.

![FightUntitled](https://user-images.githubusercontent.com/65551956/235381561-9862d028-6448-4f7e-84ea-ec6c99a4aa94.png)

![Untitled](https://user-images.githubusercontent.com/65551956/235381144-6ebd0abd-3575-465c-aff4-375701125d57.png)

**Comment by Arackulele** [comment]
His is already fixed  will be in the next release as well
