### ISSUE TITLE
Challenge level > 5?

### ISSUE THREAD

**Issue by Mancubuster** [Arackulele/GrimoraMod#151]
Hello,

I have been going through some Grimora Runs using Kaycee's Mod.  I enjoy the challenge that comes with the different starter decks.  However, after every victory the challenge level remains at 5.  I noticed that you have a hell mode that requires 80 challenge points.  Have you programmed specific circumstances that will increase the challenge level beyond 5, or is that expected from more updates to come?

**Comment by Arackulele** [comment]
Grimora mod does not increase the challenge levels because of steam achievements, every challeneg and deck etc is unlocked from the start because of that too
