### ISSUE TITLE
Frost giant not dealing any damage

### ISSUE THREAD

**Issue by VioletSkies19** [Arackulele/GrimoraMod#154]
when frost giant attacks an empty space on the board it doesn't deal any damage. the animation is also messed up

**Comment by VioletSkies19** [comment]
it still damages cards

**Comment by VioletSkies19** [comment]
happens with normal giants too. also noticed they ignore waterborne cards

**Comment by Arackulele** [comment]
closing this as i genmuinly have no idea what you are talking about, sorry
