### ISSUE TITLE
Not Being able to enter the Final Boss Fight!

### ISSUE THREAD

**Issue by TrueSerpentKing** [Arackulele/GrimoraMod#156]
![Untitled](https://user-images.githubusercontent.com/65551956/235779443-e1abfdb8-fbc0-48bd-b5f1-b33aa1545b60.png)
![Untitd](https://user-images.githubusercontent.com/65551956/235779744-93ba6faf-d083-459f-b5e4-4de7314a0a4f.png)

**Comment by TrueSerpentKing** [comment]
Restarting The game fixed the problem.

**Comment by inversefireman** [comment]
for one reason or another the top left square sometimes just doesnt work

**Comment by Arackulele** [comment]
Top left square issue, closing this as the title isnt accurate and its also a duplicate issue
