### ISSUE TITLE
"Goodbye, Luke"

### ISSUE THREAD

**Issue by inversefireman** [Arackulele/GrimoraMod#158]
Grimora's line after winning a Kaycees Mod run, being "Goodbye, Luke" currently does not line up with existing lore

**Comment by inversefireman** [comment]
![image](https://user-images.githubusercontent.com/131537927/235993219-a11ed082-7985-4d8f-bbf9-2ed3f5723d0d.png)
this line should also be changed

**Comment by SarahKirksey** [comment]
Personally, I think that, overall, her speeches need to be removed and/or shortened for Kaycee's Mod runs.

**Comment by keks307** [comment]
Lore gets a revamp anyways, so this error is now outdated and can be ignored by all affected party members. If you wish to consult to anybody but me, then please send a message to your local HOA. Thank you.
