### ISSUE TITLE
sentry arm is backwards

### ISSUE THREAD

**Issue by inversefireman** [Arackulele/GrimoraMod#163]
https://user-images.githubusercontent.com/131537927/236643466-41da06b0-51c3-4408-97ef-9f58fed07095.mp4

**Comment by Arackulele** [comment]
it just sometimes isnt positioned correctly, idk man

**Comment by Arackulele** [comment]
closed this as i have no idea what causes it, its a visual buig ( doesnt affect gameplay ) and works most of the time
