### ISSUE TITLE
softlock of unknown cause in phase 3 of Sawyer 

### ISSUE THREAD

**Issue by VioletSkies19** [Arackulele/GrimoraMod#164]
locked just after I finished my turn
![A26A2076-EEA7-48A3-ABE3-31AB623BB690](https://user-images.githubusercontent.com/13618349/236654098-229c27bf-5270-4a7f-a53e-88ad750f1f26.png)

[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
GrimoraMod.CardRelatedExtension.GetRandomItem[T] (System.Collections.Generic.List`1[T] self) (at <4f4d718f1f32405c9fffa07321d40b34>:0)
GrimoraMod.GrimoraModSawyerBossSequencer+<OnTurnEnd>d__7.MoveNext () (at <4f4d718f1f32405c9fffa07321d40b34>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by Arackulele** [comment]
fixed in the new beta
