### ISSUE TITLE
Apparation did a silly and froze my game

### ISSUE THREAD

**Issue by Jghbug7** [Arackulele/GrimoraMod#165]
While in an Ankh fight, the rule was "every second card that dies deals all cards 1 damage" and this caused 6 cards to die, one of which was a leader bifur cold front apparation, which may have been the issue?

this is my error log
[Error  : Unity Log] InvalidOperationException: Collection was modified; enumeration operation may not execute.
Stack trace:
System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
DiskCardGame.GlobalTriggerHandler+<TriggerNonCardReceivers>d__20.MoveNext () (at <4bde92741da1454db82522c215e393a6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by Arackulele** [comment]
these ankh fights have been removed, therefore this bug will no longer occur given these circumstances
