### ISSUE TITLE
Sniper + AOE strike doesn't work

### ISSUE THREAD

**Issue by Nevernamed22** [Arackulele/GrimoraMod#166]
Cards with sniper and AOE strike don't attack multiple times, they still just strike once. 
Even if it didn't give you five sniper shots on the enemy, one imagines that it would at least give you the ability to choose three spaces to attack. Perhaps even let you choose 3 enemy spaces and then force you to choose 2 player spaces, though I know how hard that would be to code.
Regardless, the sigil combo of Sniper and AOE Strike should at least do _something_.

**Comment by Arackulele** [comment]
this is just how the game handles attacking sigils, i dont really consider this a bug and will close this
