### ISSUE TITLE
Pharaoh's challenge softlock

### ISSUE THREAD

**Issue by AntasmaEX2004** [Arackulele/GrimoraMod#172]
the challenge is "whenever a second card dies, you are dealt 1 damage and one of your cards gains 1 power" i had many brittle cards so eventually the game softlocked after applying the 1 damage. here's the error.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DiskCardGame.Card.RenderCard () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.PlayableCard.UpdateStatsText () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.PlayableCard.OnStatsChanged () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.PlayableCard.ManagedUpdate () (at <4bde92741da1454db82522c215e393a6>:0)
FrameLoopManager.ExecuteIteration (FrameLoopManager+IterationType type) (at <4bde92741da1454db82522c215e393a6>:0)
FrameLoopManager.Update () (at <4bde92741da1454db82522c215e393a6>:0)

**Comment by Arackulele** [comment]
fixed
