### ISSUE TITLE
davy jones emission breaks with elec chair

### ISSUE THREAD

**Issue by inversefireman** [Arackulele/GrimoraMod#173]
![image](https://github.com/Arackulele/GrimoraMod/assets/131537927/2b1c8256-0383-4c34-b17a-fa72e1c3b9f4)

**Comment by inversefireman** [comment]
![image](https://github.com/Arackulele/GrimoraMod/assets/131537927/0c44b947-67e2-484c-9379-8f73aa391c2d)
works in my hand though??? weird

**Comment by inversefireman** [comment]
OHH NO its because of imbued okay, im dumb

**Comment by Arackulele** [comment]
closed for obvious reasons
