### ISSUE TITLE
"every second card that dies, player takes one damage, grimoras cards attack decreases" softlock

### ISSUE THREAD

**Issue by inversefireman** [Arackulele/GrimoraMod#181]
https://github.com/Arackulele/GrimoraMod/assets/131537927/91cb29ec-c79a-45ce-aa0a-2e45e4c2bbe7

**Comment by Arackulele** [comment]
possibly fixed in the new patch? not sure

**Comment by Arackulele** [comment]
this version of ankh battles no longer exists
