### ISSUE TITLE
item bug they are interactable but invisible they are invisible when they are in your pack too, even after returning to the start screen

### ISSUE THREAD

**Issue by inversefireman** [Arackulele/GrimoraMod#182]
https://youtube.com/clip/Ugkx-8nEy_TG4U4idy-mXxetLUDTnMrgYgU2

**Comment by inversefireman** [comment]
this is happening in all acts, but only to custom items, vanilla items are unchanged

**Comment by Arackulele** [comment]
Closing because this is an api bug
