### ISSUE TITLE
Softlock in Kaycee boss

### ISSUE THREAD

**Issue by atrum32** [Arackulele/GrimoraMod#185]
After the transition to the second phase I am unable to play any cards or end my turn
![image](https://github.com/Arackulele/GrimoraMod/assets/103965108/953a3093-29a8-40e2-837e-3a3c0acc6a5e)
![image](https://github.com/Arackulele/GrimoraMod/assets/103965108/cae8a22e-1930-40b7-9455-161b97d6a0ca)

**Comment by Arackulele** [comment]
has this not been fixed, this issue occurs because of a bug i already fixed, please comment if this happens again

**Comment by Arackulele** [comment]
fixed
