### ISSUE TITLE
Free cards were not being drawn by fair hand correctly when Double Soulless Challenge was active

### ISSUE THREAD

**Issue by OrochiUmbra** [Arackulele/GrimoraMod#192]
![image](https://github.com/Arackulele/GrimoraMod/assets/105059766/ee3e8f22-e459-44c8-8530-5d99784a9021)
![image](https://github.com/Arackulele/GrimoraMod/assets/105059766/b0b8b2ca-efd6-4638-a4d9-ebbeadb6ffbf)

**Comment by Arackulele** [comment]
this isnt an issue? Fair hand just gives you cards that are free or cost one bone ( or 2 if you dont have those in your deck ). Since you drew Willo there which is 1 bone cost it is working as intended
