### ISSUE TITLE
Softlock when death happens prematurely

### ISSUE THREAD

**Issue by mallardj** [Arackulele/GrimoraMod#195]
Two instances:

When a unit with the sentry sigil kills a card I place down that is about to receive a lit fuse (from the corresponding challenge), a softlock occurs.

When the pharaoh gimmick kills multiple cards in a turn due to a unit dying (all cards receive one damage per second card death), a softlock occurs.

**Comment by mallardj** [comment]
Here is the corresponding code.

`[Error  : Unity Log] InvalidOperationException: Collection was modified; enumeration operation may not execute.
Stack trace:
System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
DiskCardGame.GlobalTriggerHandler+<TriggerNonCardReceivers>d__20.MoveNext () (at <4bde92741da1454db82522c215e393a6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)`

**Comment by Arackulele** [comment]
this has been fixed, youre probably running an old version
