### ISSUE TITLE
Apparition keeps bricking my game when it dies

### ISSUE THREAD

**Issue by Jghbug7** [Arackulele/GrimoraMod#197]
When apparition dies the game softlocks and you can still interact with objects by hovering over them etc. but it is the "enemy" turn so you cant play cards, use hammer, or draw.

[Error  : Unity Log] ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
Stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Collections.Generic.List`1[T].GetRange (System.Int32 index, System.Int32 count) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
GrimoraMod.HauntedSlot+<OnOtherCardAssignedToSlot>d__5.MoveNext () (at <20cc2a3ac2eb4e799f758561ef1eb675>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by Arackulele** [comment]
cant recreate this, please reopen or like make a new issue if this happens again
