### ISSUE TITLE
Ourobones puppeteer softlock

### ISSUE THREAD

**Issue by SkiddyDiddy** [Arackulele/GrimoraMod#201]
Hammered a ourobones i put puppeteer on with the chair, Game softlocked and had to quit to menu to work around
Video example of it happening here,
https://youtu.be/sNtCcqqgfdU
Error generated in the BepInEx console  
![image](https://github.com/Arackulele/GrimoraMod/assets/139527487/e19cc565-7509-47b1-8c1a-8813d1af7d73)

**Comment by Arackulele** [comment]
https://imgur.com/a/byKd7nE

As shown in the attached video, this bug no longer happens as of the newest version
