### ISSUE TITLE
instead of just using grimoras voice, The Bone Lord should speak using his voice 

### ISSUE THREAD

**Issue by inversefireman** [Arackulele/GrimoraMod#204]
attached are the voice effects for the bone lord in act 3, theyre glitchy, but the bonelord makes glitch effects in act 1 too so i think this is passable, it'd be way better than having grimoras voice anyway
you should also have him speak using his dialogue font, Vicious Hunger
[bonelords voice.zip](https://github.com/Arackulele/GrimoraMod/files/12260833/bonelords.voice.zip)

**Comment by Arackulele** [comment]
he does
