### ISSUE TITLE
Unable to draw cards from the side deck.

### ISSUE THREAD

**Issue by ValsVonValentine** [Arackulele/GrimoraMod#207]
As said in the title, I am unable to draw cards from the side deck (skeletons)
This issue is not just limited to the Grimora mod, so I feel as if it is more of a global issue, and I would greatly appreciate any kind of assitance or solution to this problem.
Sincerely, Valentine

**Comment by ValsVonValentine** [comment]
This issue is extremely bizzare

**Comment by ValsVonValentine** [comment]
This issue is extremely bizzare. Sometimes it happens, but sometimes it seems to fix itself. I'm going to close it again for now, Until somethimg else happens.

**Comment by Werns** [comment]
I fixed it by disabling the Magnificus Mod.
