### ISSUE TITLE
Softlock when an Apparition with Frozen Away perishes (also had brittle latch)

### ISSUE THREAD

**Issue by landofrhymeandraisins** [Arackulele/GrimoraMod#213]
[Error  : Unity Log] InvalidOperationException: Collection was modified; enumeration operation may not execute.
Stack trace:
System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Collections.Generic.List`1+Enumerator[T].MoveNext () (at <44afb4564e9347cf99a1865351ea8f4a>:0)
DiskCardGame.GlobalTriggerHandler+<TriggerNonCardReceivers>d__20.MoveNext () (at <4bde92741da1454db82522c215e393a6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by Arackulele** [comment]
Uploading 8mb.video-rza-MGgQkYFr.mp4…

As shown in the video above, i cannot recreate this softlock with the abilities youve described here, maybe there was some other thing happening that caused the softlock?
