### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by dackid19** [Arackulele/GrimoraMod#215]
![image](https://github.com/Arackulele/GrimoraMod/assets/41722896/3bb8e04e-c31e-45ba-b780-0aefcf9992cb)
Weird Visual glitch. I don't think the scale and battery overlay is supposed to be happening here.

**Comment by Arackulele** [comment]
Not a bug, this is just what it looks like! This isnt even set by the mod itself, but by the games api
The api has a config setting in its config file to change the location of the energy bars
