### ISSUE TITLE
Softlock

### ISSUE THREAD

**Issue by dackid19** [Arackulele/GrimoraMod#216]
I found a softlock in the game. I gave Bal-Bal omni-strike with the electric chair. He struck one enemy, it spawned a coffin, moving him...and now he's just sitting there stalling out combat. Combat is not proceeding past this point and there is no way to continue the battle. 
![Softlock](https://github.com/Arackulele/GrimoraMod/assets/41722896/4ca26a7a-0862-4491-a181-99325931622f)

**Comment by Arackulele** [comment]
https://github.com/Arackulele/GrimoraMod/assets/73202349/a7d270fe-7cda-4a60-a6f2-0adb75e710d8



As shown in the video attached this is no longer happening as of the latest version ( this might have something to do with the elite fight effects but those are ebing reworked in the latest version as well ), tho this does show a minot mechaniacl bug where after guard dog is activated the card stops attacking more cards afterwards, tho this isnt an issue with grimora mod itself
