### ISSUE TITLE
skeliton arm asset for finishing turn fails to load 

### ISSUE THREAD

**Issue by sacra762** [Arackulele/GrimoraMod#218]
Hey i recently downloaded this mod and upon the first battle i played my cards and everything but noticed after a moment there wasn't the hand or bell or anything to start the battle or end turns I'm not sure why this is happening i have all the dependencies downloaded and everything not sure what's causing this

**Comment by Arackulele** [comment]
![image](https://github.com/Arackulele/GrimoraMod/assets/73202349/6b7cb3c1-b4fd-4708-afea-7f4197f4efc9)

Not a Bug, please stop reporting this
