### ISSUE TITLE
Softlock when dying on 3rd phase Kaycee

### ISSUE THREAD

**Issue by BlindTheBoundDemon** [Arackulele/GrimoraMod#221]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AudioController+<>c__DisplayClass43_0.<GetAudioClip>b__0 (UnityEngine.AudioClip x) (at <4bde92741da1454db82522c215e393a6>:0)
System.Collections.Generic.List`1[T].Find (System.Predicate`1[T] match) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
AudioController.GetAudioClip (System.String soundId) (at <4bde92741da1454db82522c215e393a6>:0)
AudioController.CreateAudioSourceForSound (System.String soundId, MixerGroup mixerGroup, UnityEngine.Vector3 position, System.Boolean looping) (at <4bde92741da1454db82522c215e393a6>:0)
AudioController.PlaySound3D (System.String soundId, MixerGroup mixerGroup, UnityEngine.Vector3 position, System.Single volume, System.Single skipToTime, AudioParams+Pitch pitch, AudioParams+Repetition repetition, AudioParams+Randomization randomization, AudioParams+Distortion distortion, System.Boolean looping) (at <4bde92741da1454db82522c215e393a6>:0)
AudioController.PlaySound2D (System.String soundId, MixerGroup mixerGroup, System.Single volume, System.Single skipToTime, AudioParams+Pitch pitch, AudioParams+Repetition repetition, AudioParams+Randomization randomization, AudioParams+Distortion distortion, System.Boolean looping) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.TextDisplayer.PlayVoiceSound (DiskCardGame.Emotion emotion) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.TextDisplayer.ShowMessage (System.String message, DiskCardGame.Emotion emotion, DiskCardGame.TextDisplayer+LetterAnimation letterAnimation, DialogueEvent+Speaker speaker, System.String[] variableStrings) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.TextDisplayer+<ShowUntilInput>d__37.MoveNext () (at <4bde92741da1454db82522c215e393a6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by Arackulele** [comment]
This is fixed now, will be included in the next patch
