### ISSUE TITLE
Softlock when a card dies to the "Great Flood" modifier during an Ankh battle

### ISSUE THREAD

**Issue by BlindTheBoundDemon** [Arackulele/GrimoraMod#222]
[Error  : Unity Log] InvalidCastException: Specified cast is not valid.
Stack trace:
GrimoraMod.CardRelatedExtension.GetCustomArm (DiskCardGame.CardAnimationController controller) (at <59890bd36deb4efc99777e4cf009cbd2>:0)
GrimoraMod.CardRelatedExtension+<DieCustom>d__15.MoveNext () (at <59890bd36deb4efc99777e4cf009cbd2>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by Arackulele** [comment]
made a patch taht should fix this
