### ISSUE TITLE
bonelord deck cannot be selected, giants are missing from it

### ISSUE THREAD

**Issue by inversefireman** [Arackulele/GrimoraMod#224]
![image](https://github.com/Arackulele/GrimoraMod/assets/131537927/8a0b7c3d-30ab-49c2-9e15-4f4683f42297)

**Comment by SarahKirksey** [comment]
I tested it in version 7.4.1 and it worked fine for me.

**Comment by Arackulele** [comment]
yeah this doesnt happen to anyone else

**Comment by keks307** [comment]
Fixed. Was an API bug.
