### ISSUE TITLE
Bonelord's horn vs Double-strike Ashes softlock

### ISSUE THREAD

**Issue by 0Ory** [Arackulele/GrimoraMod#226]
![Schermafbeelding 2023-11-20 001505](https://github.com/Arackulele/GrimoraMod/assets/151476851/d2131393-8ddf-4eea-a691-20d72e7ad78b)

I believe the Ashes was supposed to deal overkill damage to the card in queue, but the game bugged out sadly.

**Comment by answearingmachine** [comment]
can confirm. Issue seems to relate to dealing overkill damage to a frozen away card in the queue.
![image](https://github.com/Arackulele/GrimoraMod/assets/74689366/c655b618-1f95-4e74-a121-7f8f1c002762)
![image](https://github.com/Arackulele/GrimoraMod/assets/74689366/85ebd0bc-20fa-42eb-b0f0-9136903232aa)

**Comment by Arackulele** [comment]
https://imgur.com/a/PJQDDFZ

This does not appear to be the case
