### ISSUE TITLE
hey ara this sigil was softlocking during ankh battle nothing in console but i couldnt do anything

### ISSUE THREAD

**Issue by Pinks8n** [Arackulele/GrimoraMod#228]
![image](https://github.com/Arackulele/GrimoraMod/assets/50061387/e989aae4-cf4d-4f15-ab91-c9dae6e2a46f)
![image](https://github.com/Arackulele/GrimoraMod/assets/50061387/d837b057-dc79-4fb8-9ee2-f4d9b56b2213)

**Comment by Arackulele** [comment]
this does not include enough information, if youve been softlocked there will always be an error in the console somewhere
