### ISSUE TITLE
Softlock after using trowel

### ISSUE THREAD

**Issue by 0Ory** [Arackulele/GrimoraMod#230]
So I used the trowel item on a blue space (during a battle with flooding spaces) and it summoned a kennel. Probably an error since the kennel/card with frozen sigil is supposed to die/drown after spawning on a blue space.
![Schermafbeelding 2023-11-22 181155](https://github.com/Arackulele/GrimoraMod/assets/151476851/02b6a624-6f90-47ed-ae0d-ef3668df59dd)
![Schermafbeelding 2023-11-22 181303](https://github.com/Arackulele/GrimoraMod/assets/151476851/0e820b93-e4fb-484a-8e90-fc8339a526df)

**Comment by keks307** [comment]
Fixed in newest upcomming version.
