### ISSUE TITLE
Can't choose cards properly

### ISSUE THREAD

**Issue by MatteoDale** [Arackulele/GrimoraMod#231]
Hi Ara! Today i downloaded the newest update to the mod and i encountered this weird issue with trying to choose the cars to put on the table. I'm attaching a video of the bug. Also in another moment that i didn't record i tried right-clicking the sigil of one of the cards in my hand, but the book showed me the page of another sigil. I tried exiting and reentering multiple times but the issue is still there.

https://github.com/Arackulele/GrimoraMod/assets/121285201/7f7eba18-7f31-49da-9fdf-76d70f80cbfd

Edit: in this other clip i show the thing about the wrong sigil shown in the book

https://github.com/Arackulele/GrimoraMod/assets/121285201/26bc1eee-7925-421c-9e28-65abfd11f514

This happened right after i played the Skelephone, which i just noticed it's from the revenant mod, so it may be its problem. I did a second test placing and killing that card in the same turn and the bug happened again, so i'm 99% sure that's it. Also, once the bug happens, even the following fights keep the "bugged state". Anyway, here's the log output:

[LogOutput.log](https://github.com/Arackulele/GrimoraMod/files/13453574/LogOutput.log)

and a screenshot of the console in the moment the bug happened:

![daqd](https://github.com/Arackulele/GrimoraMod/assets/121285201/218b3fec-56f2-4522-8ac8-98b5973f8b9b)

At this point I'm pretty sure it's something about the revenant mod, in that case, I'm so sorry for needlessly bothering you.

**Comment by keks307** [comment]
These bugs are all not Grimora Mod bugs, they are caused by Revenant Mod.
