### ISSUE TITLE
Energy bars not appearing

### ISSUE THREAD

**Issue by excuses** [Arackulele/GrimoraMod#235]
Firstly, absolutely amazing mod! Exactly what I wanted after beating the game, more so than Kaycee's Mod! Should be official DLC, imo.

Anyway, my issue is the reverse of #215, in that I just did a whole playthrough without realizing that there actually IS supposed to be an energy meter somewhere. Confirmed happening with 7.4.2 and went back through at least 7.3.3 and still having the issue. No other mods installed, fresh install of Thunderstore and only installed Grimora Mod.

![image](https://github.com/Arackulele/GrimoraMod/assets/283318/536b402f-084d-463b-88bd-ce81da834b30)

Only things I see in the log that might be pertinent... 
```
[Warning: Singleton] Got null in Singleton<DiskCardGame.CandleHolder>.FindInstance
[Warning: Singleton] Got null in Singleton<DiskCardGame.ConduitCircuitManager>.FindInstance
```

but idk, attached full log anyway:
[GrimoraMod log.txt](https://github.com/Arackulele/GrimoraMod/files/13510160/GrimoraMod.log.txt)

**Comment by Arackulele** [comment]
api bug, downgrade your api for now

**Comment by keks307** [comment]
![grafik](https://github.com/user-attachments/assets/9952cd08-8b93-4b60-87b0-e38a99f63c09)
