### ISSUE TITLE
Softlock during waterlogged battle

### ISSUE THREAD

**Issue by divisionbyz0rro** [Arackulele/GrimoraMod#238]
I played a Zombie with the Skeleton Horde sigil during a waterlogged battle. This happened when it tried to kill the skeleton.

![image](https://github.com/Arackulele/GrimoraMod/assets/72713285/c29f7a44-e7e7-4d67-99d9-acd38abfc352)

**Comment by Arackulele** [comment]
this has been fixed int he latest version, are you sure you were playing with the latest patc/h?

**Comment by divisionbyz0rro** [comment]
unless r2 updated it when i wasn't paying attention, this is what i was on:

![image](https://github.com/Arackulele/GrimoraMod/assets/72713285/5c65880c-52e5-4a43-98c5-4f84e686d7de)

**Comment by keks307** [comment]
It is definitely fixed with the next update. (Ara says hi)
