### ISSUE TITLE
Softlock during Grimora Phase 3

### ISSUE THREAD

**Issue by divisionbyz0rro** [Arackulele/GrimoraMod#239]
![image](https://github.com/Arackulele/GrimoraMod/assets/72713285/6935f8fa-b753-4302-8691-1c6699138bf5)

Null reference exception when I trampled damage through the bonehorn into the one in the queue.

**Comment by Arackulele** [comment]
duplicate issue, also still not recreatable, there is some outside factor taht determines when this bug happens
