### ISSUE TITLE
minor text issues

### ISSUE THREAD

**Issue by scrybeofteeth** [Arackulele/GrimoraMod#24]
opening the rulebook gives either handy the ressurection text or ressurection the handy text, and ancient obol has the same introduction text as drowned soul ("maybe going into that well wasn't such a good idea"). aside from that, this mod is incredible so far!

**Comment by scrybeofteeth** [comment]
also I just beat kaycee and it didn't offer me a rare card, I had to exit and reenter into the next map.

**Comment by julian-perge** [comment]
There were quite a few bug fixes that were recently released, along with more cards and new chess pieces.

if you pull from this PR, or my forked repo, you should have a much more stable build.

https://github.com/Arackulele/GrimoraMod/pull/25

**Comment by scrybeofteeth** [comment]
saw the update, it seems to work now!
