### ISSUE TITLE
Softlock when card with Sentry takes out a Bone Heap brought back with Double Death

### ISSUE THREAD

**Issue by landofrhymeandraisins** [Arackulele/GrimoraMod#241]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DiskCardGame.Card.RenderCard () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.PlayableCard.UpdateStatsText () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.PlayableCard.OnStatsChanged () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.PlayableCard.ManagedUpdate () (at <4bde92741da1454db82522c215e393a6>:0)
FrameLoopManager.ExecuteIteration (FrameLoopManager+IterationType type) (at <4bde92741da1454db82522c215e393a6>:0)
FrameLoopManager.Update () (at <4bde92741da1454db82522c215e393a6>:0)

**Comment by keks307** [comment]
Fixed.
