### ISSUE TITLE
Can't play Kaycee's mod

### ISSUE THREAD

**Issue by PiedroSinistru** [Arackulele/GrimoraMod#243]
I can't play the Kayceee's mod.
I only have the GrimoraMod installed with dependencies out of Thunderstore.

https://github.com/Arackulele/GrimoraMod/assets/143136163/fa76a2e6-6095-4c3d-a807-c3fe9a1c3bce

![Captura de ecrã 2023-12-29 150540](https://github.com/Arackulele/GrimoraMod/assets/143136163/3f67e7fc-a9a8-431f-a079-825c9a92a498)

I can play GrimoraMod fine tho.

**Comment by Arackulele** [comment]
This is because you have not unlocked kcmod in the game yet, not because grimoramod is breaking
