### ISSUE TITLE
Ashes persist after Death/Reset

### ISSUE THREAD

**Issue by MajorGeneralKierkegaard** [Arackulele/GrimoraMod#246]
As the title says, my ashes remain after deaths and resets. Thus far, I have tried uninstalling and reinstalling the mod but I still have the same number of ashes and they only go up. It's neat but I'd rather not make the game artificially easier on myself. Any suggestions would be welcome. Thank you for your time.
![GrimoraMod](https://github.com/Arackulele/GrimoraMod/assets/160428245/3ccd7e27-2342-42c0-9244-cd6d908b05ed)

**Comment by MajorGeneralKierkegaard** [comment]
Quick addendum: resetting game data does not reset the ashes (It was nice to play through the game again, though).
![GrimoraMod](https://github.com/Arackulele/GrimoraMod/assets/160428245/3ee4dfcc-d679-485a-a27b-96ea7ec32449)

**Comment by keks307** [comment]
Fixed.
