### ISSUE TITLE
Game locked after beating Grimora's ice bones battle.

### ISSUE THREAD

**Issue by sonic260** [Arackulele/GrimoraMod#247]
This is on a new-ish run. The game seems to think I know about energy, but there was no tutorial on it yet, nor is there an energy bar indicator like in P03's game, so I'm wondering if this is due to a sequence break...

I'm receiving this bug on GrimoraMod v7.4.2, API 2.19.4

![image](https://github.com/Arackulele/GrimoraMod/assets/54485477/4b534201-777e-4973-a274-6ea60a5ec2cb)

**Comment by evxmas** [comment]
Same issue here, just encountered while playing through mod for first time.

**Comment by PotatoIsUs** [comment]
I believe this is caused by using both MagnificusMod and GrimoraMod together, they seem to break each other.

**Comment by keks307** [comment]
To solve this issue, please go into the Community Patch Config file and activate the Energy Drone. For other problems, please refer to the ingame disclaimer that pops up whenever you start the Mod.
