### ISSUE TITLE
Final boss soft lock.

### ISSUE THREAD

**Issue by Cransiosis** [Arackulele/GrimoraMod#248]
Bone lord did not like my bifurcated strike giant hitting him and then killing a bone to his side. The game just stopped, his side of the field like some sort of thing was supposed to happen. Nothing happened.
EDIT: Seems as though what's causing the soft lock is doing excess damage to the horns on the backboard. Perhaps the game is trying to transform them, and because they aren't valid cards it gets locked.
![Capture](https://github.com/Arackulele/GrimoraMod/assets/99849949/92faba4e-3009-4170-aebf-98ef5b81ab98)

**Comment by keks307** [comment]
It is fixed.
