### ISSUE TITLE
Can't access Challenge Unlock Screen

### ISSUE THREAD

**Issue by h0rrid0** [Arackulele/GrimoraMod#249]
After winning a run and viewing the stats screen the game throws an error (see console screenshot below) on continuing to the next screen. I am back in the menu and can continue the run I just ended just before beginning the final match (against Grimora).

![Bild_2024-03-15_183621475](https://github.com/Arackulele/GrimoraMod/assets/53529519/d8092599-c611-41dc-9799-f29549a88da3)

**Comment by Arackulele** [comment]
You seem to have other mods installed that would break this, possible an api version caused this in the past. Either way it is not an issue anymore
