### ISSUE TITLE
File cant be found Please reinstall the mod!

### ISSUE THREAD

**Issue by KirbyKid9908by** [Arackulele/GrimoraMod#255]
Whenever i try to open the mod it just says "file could not be found and checksum[long numbers] does not equal checksum[other string of long numbers]. Please reinstall the mod."

**Comment by CuteCyanGirl** [comment]
Same.

**Comment by keks307** [comment]
This is a warning and not an Error. The warning can be ignored, since the Mod will open totally fine with it.
