### ISSUE TITLE
hi ara

### ISSUE THREAD

**Issue by TheDaringDarson** [Arackulele/GrimoraMod#257]
hi ara

**Comment by Arackulele** [comment]
i hope you die in a fire

**Comment by TheDaringDarson** [comment]
> i hope you die in a fire

[https://media.discordapp.net/attachments/1254648166930841660/1273170506291609603/testa.gif?ex=66dd47ef&is=66dbf66f&hm=0d8725fc12bbe0437522fc4e3c3aa44148a7fc8a6b1db0b58c26cb67a08fc741&=&width=294&height=170](url)

**Comment by TheDaringDarson** [comment]
> i hope you die in a fire

![testa](https://github.com/user-attachments/assets/da94549b-740d-49ce-83ed-24f6c30b81eb)
