### ISSUE TITLE
Kaycee boss freezes

### ISSUE THREAD

**Issue by TheMawnster** [Arackulele/GrimoraMod#259]
Kaycee freezes when I beat her boss fight, it stops here and this is all the console says.
![Screenshot 2024-10-06 115210](https://github.com/user-attachments/assets/72a98c7c-188f-462b-8ca1-a26e321d608d)
![Screenshot 2024-10-06 115131](https://github.com/user-attachments/assets/49e0e68b-3a46-426c-95b7-14f12f553653)

**Comment by TheMawnster** [comment]
Also if I return to the main menu and come back it resets the boss

**Comment by Arackulele** [comment]
Non descript, that console screenshot doesnt show an error at all so i will close this issue
