### ISSUE TITLE
Game Stops Working :\

### ISSUE THREAD

**Issue by TosandThos** [Arackulele/GrimoraMod#262]
Hi, loving your mod and want to keep playing it, Every so often we stop being able to ring the bell or play a card, seemingly at random. Sometimes breaking a card makes it work again and sometimes it doesn't. Please see below a screenshot of the log of the last time this happened as well as the mods I have installed, including Unlock_All which I know you suggested for these kinds of issues. Hope you can help, and happy gaming!!

![image](https://github.com/user-attachments/assets/614499bb-8618-4de6-82e3-3b506601c645)

**Comment by Arackulele** [comment]
im gonna close this issue because every error ends up in the turn manager of the game breaking, meaning you have to quit out and go back into the run to fix it. Since this isnt documenting a specific error it is like submitting a bug report for "the game has errors" which is not specific enough
