### ISSUE TITLE
Softlock due to invalid deck for Fairhand

### ISSUE THREAD

**Issue by answearingmachine** [Arackulele/GrimoraMod#266]
![image](https://github.com/user-attachments/assets/920eb430-b0f4-407c-8185-aaf207cb0b94)
![image](https://github.com/user-attachments/assets/e739c230-5305-491e-98c9-954ad90775d7)
All but the warthr were in my starting deck (random option)
is there not a handler for this

**Comment by Arackulele** [comment]
Just added another layer of protection against this issue just in case this comes up again

**Comment by answearingmachine** [comment]
still having the issue
![image](https://github.com/user-attachments/assets/c351a83c-7016-4abd-9fe8-478188aa6ea2)
![image](https://github.com/user-attachments/assets/d77c6eca-6e31-4217-8329-1f9d7a2729c6)
