### ISSUE TITLE
Z-Fighting from Necromancer's Sigil in specific circumstances

### ISSUE THREAD

**Issue by f-raZ0R** [Arackulele/GrimoraMod#28]
This is really inconsistent and honestly happens too brief for me to screenshot.

Steps to Reproduce:
Have a necromancer and a gravedigger on the board.
Have your gravedigger die in combat, during the opponent's turn.
There will be 2 gravediggers overlapping, for approximately 1 second.

**Comment by julian-perge** [comment]
From the sounds of it, it sounds like it's just a visual bug. As ugly as it appears, it's working as intended.
