### ISSUE TITLE
mod is not running 

### ISSUE THREAD

**Issue by reductorpatronum** [Arackulele/GrimoraMod#87]
hello i saw the mod updated so i flipped it back on to play with it again and now the mod wont load in the code box it says this 

![Screenshot (2785)](https://user-images.githubusercontent.com/117543886/200141096-9a37619e-8c46-4ce0-b088-16f964c64b37.png)
and although it boots the kaycees mod screen look like default and none of the buttons work please help.

**Comment by OrochiUmbra** [comment]
PO3 Kaycee Mod is currently not compatible with Grimora Mod, please disable it and try again. 
If the problem persists, please reinstall everything and enable ONLY Grimora mod related mods, you might want to back up your save before doing any mod related activities.
