### ISSUE TITLE
is there a way to go back to the normal game?

### ISSUE THREAD

**Issue by cutefoxix** [Arackulele/GrimoraMod#90]
so, I've played this mod for a bit, and I'm honestly not very good at it. I can't get very far without dying. I tried to just turn the mod off, but when I go to play normally I go to where the mod starts except there are no cards, meaning I can't progress. Do I have to finish the mod to be able to play the game normally again?

**Comment by OrochiUmbra** [comment]
its been warned that you must back up the save file before doing any modded activity to avoid save corruption, grimora mod at its current state messes with your current save progression. 
if you wish to play the gaim normally, you might want to utilize the ingame debug option pressing "Shift + K + M" at main menu to choose the progression you may want to continue on, but resetting your save file in the process. 
we are planning to move the save file of grimora mod seporatly from normal progression to avoid similar issues, thx for reporting.

**Comment by Arackulele** [comment]
Not an issue / fixed
