### ISSUE TITLE
Completing a Grimora Run with Kaycee's Mod

### ISSUE THREAD

**Issue by Mancubuster** [Arackulele/GrimoraMod#92]
I recently attempted to do a Grimora Run via Kaycee's Mod.  I wanted to know how anyone can complete a Grimora Run since after I beat Grimora, the screen shifts back to a Leshy map? There was no phasing out or deletion of assets as was done during the normal Grimora Mod.  Instead it seems like I had to defeat Leshy with a starter Deck from Grimora's mod.  That did not seem to work as when I tried to select a bottom totem (for e.g.), the game froze.  

Are there any software patches to circumvent this issue or is the Grimora mod not ready to integrate with Kaycee's mod? I do enjoy the skill challenges arranged and eager to see what new decks (besides the 4 provided), will be available.

**Comment by Arackulele** [comment]
fixed
