### ISSUE TITLE
Grimora Run with Kaycee's Mod completed statistics

### ISSUE THREAD

**Issue by Mancubuster** [Arackulele/GrimoraMod#98]
Hello,

The last time I addressed this problem, I think it was only half-solved.  After defeating Grimora through Kaycee's Mod, the red lines of programming code fills up the screen and then I am brought back to Leshy's cabin.  For some reason the screen freezes up with the map unraveling and 3 light candles.  Leshy does not talk and there is nothing else on the map.  

I was under the impression that once you beat a Grimora Run with Kaycee's mod, the screen would clear and show your statistics.  E.g. Misplays, most damage on a scale, bosses defeated.  On top of that, there would be cards and starter decks unlocked, and then revert back to the main menu on a black background.  I know there are 4 starter decks still hidden.

Something else of note, the challenge levels have not increased with each completed run with KM.  It just stays at 5 never going higher.  Is there any way to increase that?

**Comment by Arackulele** [comment]
The fix for this will be released with the next update, which ahould release in the next few days
